// Review export: extracts the annotated code range and builds the Markdown
// artifact. Pure — no TUI or filesystem side effects (the caller writes the
// file and reports status).

import { type FileDiff } from "./git.ts"
import {
  type Annotation,
  type Severity,
  type Status,
  type Source,
  parseCommentKey,
} from "./model.ts"

export const getRangeContent = (
  fd: FileDiff,
  startLine: number,
  endLine: number,
  side: "old" | "new" = "new",
): string => {
  const result: string[] = []
  let newCounter = 0
  let oldCounter = 0
  let inHunk = false
  for (const l of fd.lines) {
    if (l.startsWith("@@ ")) {
      const m = l.match(/@@ -(\d+)(?:,\d+)? \+(\d+)/)
      if (m) {
        oldCounter = parseInt(m[1]!, 10)
        newCounter = parseInt(m[2]!, 10)
      }
      inHunk = true
    } else if (!inHunk) {
      // Skip the file header (diff --git, index, --- a/, +++ b/) that precedes
      // the first hunk — otherwise its lines are miscounted as content.
      continue
    } else if (l.startsWith("+") && side === "new") {
      if (newCounter >= startLine && newCounter <= endLine)
        result.push(l.slice(1))
      if (newCounter > endLine) break
      newCounter++
    } else if (l.startsWith("-") && side === "old") {
      if (oldCounter >= startLine && oldCounter <= endLine)
        result.push(l.slice(1))
      if (oldCounter > endLine) break
      oldCounter++
    } else if (!l.startsWith("+") && !l.startsWith("-") && l) {
      const counter = side === "old" ? oldCounter : newCounter
      if (counter >= startLine && counter <= endLine) result.push(l.slice(1))
      if (counter > endLine) break
      newCounter++
      oldCounter++
    }
  }
  return result.join("\n")
}

export const buildReviewMarkdown = (
  comments: Map<string, Annotation>,
  fileDiffs: FileDiff[],
  prompt: string,
): string => {
  const byFile = new Map<
    string,
    Array<{
      startLine: number
      endLine: number
      side: "old" | "new"
      ann: Annotation
    }>
  >()
  for (const [key, ann] of comments) {
    const { file, side, startLine, endLine } = parseCommentKey(key)
    if (!byFile.has(file)) byFile.set(file, [])
    byFile.get(file)!.push({ startLine, endLine, side, ann })
  }
  const reviewSections = [
    `# Code Review\n\nGenerated by revu on ${new Date().toISOString()}\n`,
  ]
  for (const [file, entries] of byFile) {
    reviewSections.push(`## \`${file}\`\n`)
    const fd = fileDiffs.find((f) => f.file === file)
    const ext = file.split(".").pop()?.toLowerCase() ?? ""
    for (const { startLine, endLine, side, ann } of entries.sort(
      (a, b) => a.startLine - b.startLine,
    )) {
      const content = fd ? getRangeContent(fd, startLine, endLine, side) : ""
      const codeBlock = content ? `\`\`\`${ext}\n${content}\n\`\`\`\n` : ""
      const sideLabel = side === "old" ? " (removed)" : ""
      const statusLabel =
        ann.status && ann.status !== "open" ? ` — _${ann.status}_` : ""
      const lineRef =
        startLine === endLine
          ? `Line ${startLine}${sideLabel}`
          : `Lines ${startLine}–${endLine}${sideLabel}`
      // Conventional-comment prefix driven by severity (blocker/concern/nitpick).
      const prefix = ann.severity ? `**${ann.severity}:** ` : ""
      const commentText = (prefix + ann.text)
        .split("\n")
        .map((l) => `> ${l}`)
        .join("\n")
      reviewSections.push(
        `### ${lineRef}${statusLabel}\n${codeBlock}${commentText}\n`,
      )
    }
  }
  const header = prompt.trim() ? `${prompt.trim()}\n\n---\n\n` : ""
  return header + reviewSections.join("\n")
}

// Machine-readable review for agents/tooling: one entry per annotation with
// resolved triage fields and the captured code range.
export interface JsonReviewComment {
  file: string
  startLine: number
  endLine: number
  side: "old" | "new"
  severity: Severity | null
  status: Status
  source: Source
  text: string
  code: string
}

export interface JsonReview {
  prompt: string
  comments: JsonReviewComment[]
}

export const buildReviewJson = (
  comments: Map<string, Annotation>,
  fileDiffs: FileDiff[],
  prompt: string,
): JsonReview => {
  const out: JsonReviewComment[] = []
  for (const [key, ann] of comments) {
    const { file, side, startLine, endLine } = parseCommentKey(key)
    const fd = fileDiffs.find((f) => f.file === file)
    out.push({
      file,
      startLine,
      endLine,
      side,
      severity: ann.severity ?? null,
      status: ann.status ?? "open",
      source: ann.source ?? "human",
      text: ann.text,
      code: fd ? getRangeContent(fd, startLine, endLine, side) : "",
    })
  }
  out.sort((a, b) => a.file.localeCompare(b.file) || a.startLine - b.startLine)
  return { prompt, comments: out }
}
